### ISSUE TITLE
practica Melissa 

### ISSUE THREAD

**Issue by mel-16** [SistemasTecTlaxiaco/conexion-bases-de-datos-los-3-mosqueteros-topicos#2]
[Practica Melissa SolanoVasquez.pdf](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-los-3-mosqueteros-topicos/files/8914342/Practica.Melissa.SolanoVasquez.pdf)

**Comment by JudithReynaCS** [comment]
Calificación:14.5%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
